# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Simple Mediatr
      run: |
        dotnet pack ./base-mediatr/base-mediatr.csproj --configuration Release --no-build --output ./artifacts  
        
    - name: Publish Simple Mediatr
      run: |
         dotnet nuget add source --username ekinbulut --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ekinbulut/index.json"
         dotnet nuget push "./artifacts/*.nupkg"  --api-key ${{ secrets.MY_GITHUB_PAT }} --source "github" --skip-duplicate
